version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ${{ steps.task-def.outputs.task-definition }}  # Dynamically set task definition ARN
        LoadBalancerInfo:
          ContainerName: "memorylane-container"
          ContainerPort: 5000
        PlatformVersion: "LATEST"
