version: "0.0"
Resources:
  - TargetService:
      Type: "AWS::ECS::Service"
      Properties:
        TaskDefinition: "${{ steps.register-task-def.outputs.task_definition_arn }}"
        LoadBalancerInfo:
          ContainerName: "memory-lane"
          ContainerPort: 5000
        PlatformVersion: "LATEST"
Hooks:
  BeforeInstall:
    - Location: "arn:aws:lambda:us-east-1:650251709711:function:LLambdaFunctionToValidateBeforeInstall"
  AfterInstall:
    - Location: "arn:aws:lambda:us-east-1:650251709711:function:LambdaFunctionToValidateAfterInstall"
  AfterAllowTestTraffic:
    - Location: "arn:aws:lambda:us-east-1:650251709711:function:LambdaFunctionToValidateAfterTestTrafficStarts"
  BeforeAllowTraffic:
    - Location: "arn:aws:lambda:us-east-1:650251709711:function:LambdaFunctionToValidateBeforeAllowingProductionTraffic"
  AfterAllowTraffic:
    - Location: "arn:aws:lambda:us-east-1:650251709711:function:LambdaFunctionToValidateAfterAllowingProductionTraffic"
